name = "etf_js"
version = "0.2.1"
target = "javascript"
description = "Convert erlang ETF encoded binaries to (reasonable) JavaScript equivalents"
licences = ["MIT"]
repository = { type = "github", user = "arnu515", repo = "erlang-etf.js" }

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_javascript = ">= 1.0.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
